
version: "3"

services:
  app:
    build: .
    image: url-shortener:latest
    container_name: app
    ports:
    - "8080:8080"
    networks:
      - main

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - app
    networks:
      - main

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
    - "3000:3000"
    networks:
      - main
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  main:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
